version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: docker-symfony4-webserver
    working_dir: /application
    volumes:
        - ./app:/application
        - ./logs:/var/log/nginx
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
       - "8000:80"
