version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: docker-symfony4-webserver
    working_dir: /application
    volumes:
      - ./app/website-skeleton:/application
      - ./logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
       - "8000:80"
  php-fpm:
    build: app
    container_name: docker-symfony4-php-fpm
    working_dir: /application
    volumes:
      - ./app/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ./app/website-skeleton:/application
      - var:/application/var
      - vendor:/application/vendors
volumes:
  var:
  vendor:
